- name: install cron job (run ansible-pull every 10min)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "10"
    job: "sudo /usr/bin/ansible-pull -o -U https://github.com/Alan-Ng-72/Ansible.git >> /var/log/ansible.log"
